service: aws-lambda-node-logger-test

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  stage: dev
  logRetentionInDays: 30

functions:
  emergency:
    handler: handler.jsTest
    events:
      - http:
          path: tests/js
          method: get
          cors: true
