service: aws-lambda-node-logger-test

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  stage: dev
  logRetentionInDays: 30
  environment:
    AWS_LAMBDA_NODE_LOGGER_SLACK_TOKEN: ${env:AWS_LAMBDA_NODE_LOGGER_SLACK_TOKEN}
    AWS_LAMBDA_NODE_LOGGER_SLACK_CHANNEL: ${env:AWS_LAMBDA_NODE_LOGGER_SLACK_CHANNEL}

functions:
  jsTest:
    handler: handler.jsTest
    events:
      - http:
          path: tests/js
          method: get
          cors: true
  tsTest:
    handler: dist/src/handler.tsTest
    events:
      - http:
          path: tests/ts
          method: get
          cors: true
